### ISSUE TITLE
NoMethodError: undefined method `wait_readable' for #<StringIO:...>

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-prompt#104]
I have upgraded one of my gems to use the latest tty-prompt 0.19, and then my tests failed with this error:

```
NoMethodError: undefined method `wait_readable' for #<StringIO:...>
```

Then, I noticed that you have patched StringIO with `#wait_readable` in your `spec_helper`, so I did the same and my tests pass as well.

https://github.com/piotrmurach/tty-prompt/blob/700fb96fc8f6c43b4e3ef2dc184ef72edb32b358/spec/spec_helper.rb#L20-L24

Can you explain what was the change that requires this patch?

**Comment by piotrmurach** [comment]
The change that required this is the `keypress` prompt. 

First of all, it was broken in Windows PowerShell which is not great. 

More importantly, though, I was using threads to display the timeout message with the io blocking. So I had two issues. Threads that may or may not be implemented and the blocking io. So I decided to get rid of timers dependency and threads since they introduced a lot of complexity for just a single prompt and didn't work on all platforms. 

I had to figure out a way to display timeout with a non-blocking io. I changed the `tty-reader` implementation to do non-blocking read. Doing just non-blocking read created a busy loop of reads that were impossible to capture reliably. I took me days of trying many solutions. And then I came across a way to do non-blocking wait for io read operations. It works very well and does exactly what I need. It is an extension to normal io operations but the stringio doesn't mock this operation by default.

Hope this answers your question.
