### ISSUE TITLE
`#select` return value inconsistent when intentionally trying to return `nil`

### ISSUE THREAD

**Issue by ttilberg** [piotrmurach/tty-prompt#160]
### Describe the problem
Using `#select` is inconsistent when wishing to return `nil`.

Given a label `None` to represent `nil`, and a list of other objects labeled by their name, the return value is either the label, or the value, instead of always the value.

### Steps to reproduce the problem

```ruby
Guy = Struct.new(:id, :name)

candidates = [
  Guy.new(1, "Buddy"),
  Guy.new(2, "Pal")
]

prompt = TTY::Prompt.new
winner = prompt.select "Which Guy?" do |menu|

  # Label first option as "None", expected to return `nil`
  menu.choice "None", nil

  candidates.each do |candidate|
    #  Label in menu as candidate name, expected to return full candidate object.
    menu.choice candidate.name, candidate
  end

end
```

Additionally, using the Hash argument syntax results the same:

```rb
options = {"None" => nil}
options.merge!(candidates.map { |cand| [cand.name, cand] }.to_h)
# => {"None"=>nil, "Buddy"=>#<struct Guy id=1, name="Buddy">, "Pal"=>#<struct Guy id=2, name="Pal">}

winner = prompt.select("Which Guy?", options)
```

### Actual behaviour
If `None` is selected, `winner` is assigned `"None"`, the **first argument** to `menu#choice`.

For other options, the full object is assigned, the **second argument** to `menu#choice`.

### Expected behaviour
The second argument to `#choice` to be assigned regardless of its falsiness or niliness. As I understand it from the readme, the first arg is a label, the second value is the value. I took a quick glance at the source, and wasn't able to quickly grok how this gets assembled. I suspect [here-ish](https://github.com/piotrmurach/tty-prompt/blob/e4d60489dd77d43191226e3fb926c6b7bb398ad5/lib/tty/prompt/list.rb#L201)

If you disagree that this is a bug, but wish to keep it as intended, or, if it cannot be reasonably fixed, can you describe how to create a "nil" option similar to above, and can we update the Readme with this use-case?

### Describe your environment

* OS version: MacOS Catalina 10.15.7
* Ruby version: 2.7.2
* TTY::Prompt version: 0.23.0

**Comment by piotrmurach** [comment]
Hi Tim,

Good to hear from you again and see that you're getting addicted to tty gems 😜
 
You're right this is a bug. I suspect the culprit is the `TTY::Prompt::Choice` that coerces values into choice objects. It probably 'struggles' with distinguishing between a `nil` value and no value that is `nil` because it wasn't provided in the first place. I'll take a look and see what can be done to resolve this.

**Comment by piotrmurach** [comment]
Fixed the choice coercion to distinguish between no value being set and a value set to nil. Can you please check against the master branch that this is also working for you?

**Comment by ttilberg** [comment]
Thanks @piotrmurach! Confirmed that this is working as expected and can be closed. Thank you!

**Comment by DannyBen** [comment]
This fix caused a massive break for me, I expected such a change to be at least a minor release number, and not a patch.

In my code I used to have cases where this type of Hash was used to present a simple menu:

```ruby
{ "One" => nil, "Two" => nil }
```

I know it is not ideal, and I am not even sure I intended for it to be like it, but it was, and it worked in previous versions. The new version broke it, as demonstrated by the code below:

```
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"

  # gem 'tty-prompt', '0.23.0'   # works
  gem 'tty-prompt', '0.23.1'   # fails
end

prompt = TTY::Prompt.new
options = { "One" => nil, "Two" => nil }
response = prompt.select "Choose", options
p response
```

I already fixed it on my side, but thought I should post this here for posterity.

**Comment by piotrmurach** [comment]
Hi Danny,

Thank you for making me aware of this! Apologies didn't intend to break your gems. I debated whether this should be a patch or minor but decided that this shouldn't be a breaking change since the value is now an actual value. I reasoned that the case when choices are provided as Hashes with nil values is an edge case. And I was obviously wrong. Before I released the gem I checked a few other projects to see if I may break something. This is to say I tried to make sure this doesn't affect anyone.

I run your snippet for both the `{ "One" => nil, "Two" => nil }` and `[{ "One" => nil}, {"Two" => nil }]` and they work for both  the `v0.23.0` and `v0.23.1`. The menu is displayed fine as it should because the keys are used for rendering labels. What has changed is the return value. In past, the `nil` value would be 'automatically' substituted with the key label. Now it's not, it returns whatever the value is.

**Comment by DannyBen** [comment]
> I reasoned that the case when choices are provided as Hashes with nil values is an edge case. And I was obviously wrong.

You were not necessarily wrong, I feel at least for me it was an edge case that I do not believe I created intentionally - it's just that my code sends user-generated options through the same function, which happened to convert array options (`["one", "two"]`) to hashes with `nil` values.

> What has changed is the return value.

Yup. This was exactly what I observed, and can be seen in the repro code.

Anyways - I don't even think I would have done anything different if I were in your shoes, and I know this is especially a problem in "non-semver" 0.x versions. The new behavior makes total sense. I really just posted it here so we have the proper chain of events.

**Comment by piotrmurach** [comment]
@DannyBen Thanks for your understanding of my maintainer's plight. In future, I will ping you when I'm making changes that may potentially affect you. And as far as `v1.0.0` version is concerned. Two things need to happen, one is support for 'autocompletions' which I'm slowly progressing in the `tty-reader` project and two a plugin-based system so that it's easy to add your own extensions.

**Comment by DannyBen** [comment]
> I will ping you when I'm making changes that may potentially affect you

I appreciate the gesture, but don't worry about it. You can't be expected to notify users personally :)

In my more sensitive gems, I will lock to a stricter version, and I am considering even running the CI tests on a monthly schedule. Everything I do usually has 100% test-coverage, so we can easily use automation and version restriction to reduce failure rate.
