### ISSUE TITLE
Feature request: Prompt for value or optionally go into editor mode

### ISSUE THREAD

**Issue by ngan** [piotrmurach/tty-prompt#164]
### Describe the problem
We have a scenario where we'd like to `ask` for a simple value on the command line. However, sometimes the value can be multiline and we believe putting folks inside an editor would be more helpful.

I understand that there's a multiline feature for tty-prompt but users are not accustom to this. They typically just want to hit ENTER.

It would be cool if there was a prompt like this...

```
Press Ctrl+E to enter editor
What is your config value?
```

They can type out the config value and press enter, or they can hit ctrl+e to be thrown into the editor. (We use tty-editor for editor interactions 👍)

Is there a way to implement this with the existing tty prompt/reader/editor blocks?

**Comment by piotrmurach** [comment]
Hi Ngan 👋 

Thanks for using `tty-prompt`.

> I understand that there's a multiline feature for tty-prompt but users are not accustom to this. They typically just want to hit ENTER.

Curious to know how would you handle multiline input when ENTER is used to finish input? What key would you use to move to a new line? I'm open to suggestions on how else could this be implemented?

One way you could achieve your requirement is to listen for the `keyctrl_e` event and use the `keypress` prompt. The user then has a choice to either open an editor or confirm they wish to input via `multiline` prompt:

```ruby
require "tty-editor"
require "tty-prompt"

content = ""
prompt = TTY::Prompt.new
prompt.on(:keyctrl_e) do
  Tempfile.create("temp-file") do |file|
    TTY::Editor.open(file.path)
    content = ::File.read(file.path)
  end
end

answer = prompt.keypress("Press Ctrl+E to open editor or Enter to input", keys: [:return, :ctrl_e])
if answer == "\r"
  content = prompt.multiline("What is your config value?")
end
puts content
```

The way tty components are written is to maximise ways they can be composed. Because of this, I don't believe this is a feature request. It can be achieved in various ways and doesn't add a fundamental input that would enhance `tty-prompt`.

Hope the example helps you achieve what you need.

**Comment by ngan** [comment]
Thank you for your response. I might have not be super clear in my original question. So I’d like to do a single line prompt (“ask”) so the user can either: start entering their config value and then hit enter to finish, OR press control+e at any point to go into editor.
