### ISSUE TITLE
Using an enumerator for choices

### ISSUE THREAD

**Issue by sled** [piotrmurach/tty-prompt#165]
### Describe the problem
When supplying an enumerator as choices to a select menu, the menu breaks.

My goal is to supply an enumerator which navigates a JSON API with paging and feed a `TTY::Prompt` select menu.

```rb
items = Enumerator.new do |yielder|
  next_page_uri = FIRST_PAGE_URI

  loop do
    page = fetch_json(next_page_uri)
    page['items'].each { |item| yielder << item }
    break unless page['next']
    next_page_uri = URI(page['next'])
  end
end

prompt.select("Choose your item:", items, per_page: 10)
```

### Steps to reproduce the problem

A simplified example:

```rb
prompt = TTY::Prompt.new
letters = ["A", "B", "C", "D", "E"].to_enum
prompt.select("Choose your letter?", letters, per_page: 2)
```

### Actual behaviour
Incorrect output, arrow keys not functional.

```sh
Choose your letter? (Press ↑/↓ arrow to move and Enter to select)
‣ #<Enumerator:0x00007fa2af09e5a8>
```

### Expected behaviour
I'd expect it to be possible to navigate the menu and getting the correct text labels.

### Describe your environment

* OS version: MacOS 11.2
* Ruby version: 2.7.3
* TTY::Prompt version: v0.23.1

**Comment by sled** [comment]
I managed to get it working by manually creating a list:

```rb
prompt = TTY::Prompt.new
letters = ["A", "B", "C", "D", "E"].to_enum

list = TTY::Prompt::List.new(prompt, per_page: 2)
list.call("Choose a letter", letters)
```

but `TTY::Prompt::List` seems to iterate all elements, defeating the purpose of having a paged enumerator, e.g:

```rb
numbers = Enumerator.new do |yielder|
  count = 1
  loop do
    puts "yield!"
    yielder << count
    count += 1
    break if count > 5
  end
end

list = TTY::Prompt::List.new(prompt, per_page: 2)
list.call("Choose a number", numbers)
```

will result in:

```sh
yield!
yield!
yield!
yield!
yield!
Choose a number (Press ↑/↓/←/→ arrow to move and Enter to select)
‣ 1
  2
```

this is especially a problem if you have an "infinite" list of things, like a fibonacci sequence. This will block forever:

```rb
fib = Enumerator.new do |y|
  a = b = 1
  loop do
    y << a
    a, b = b, a + b
  end
end

list = TTY::Prompt::List.new(prompt, per_page: 10)
list.call("Choose your favorite fibonacci number", fib)
```

**Question**
Do you think it's possible to adapt `TTY::Prompt::List` so that it does not iterate all elements beforehand but rather uses [Enumerator#peek](https://ruby-doc.org/core-2.6/Enumerator.html#method-i-peek) to check if there are more elements to paginate?

**Comment by sled** [comment]
Found a way to achieve this, but it's a bit messy because it checks if the cursor is at the end of the list by accessing an instance variable.

```rb
fib = Enumerator.new do |y|
  a = b = 1
  loop do
    y << a
    a, b = b, a + b
  end
end

prompt = TTY::Prompt.new
list = TTY::Prompt::List.new(prompt)

prompt.on(:keydown) do |event|
  if list.instance_variable_get(:@active) == list.choices.length
    # end of list reached, load more
    list.choice(fib.next)
  end
end

# start with 5 numbers in the list
result = list.call("Select a number: ", 5.times.map { fib.next })

puts "You chose: #{result}"
```

**Comment by piotrmurach** [comment]
Hi Simon 👋 

Thanks for using `tty-prompt` and submitting this issue.

When I read this issue I got confused by this sentence:

> When supplying an enumerator as choices to a select menu, the menu breaks.

Would you mind explaining where did the documentation/examples lead you to believe that enumerators are supported? I'd like to remedy this as this gem has never supported such a use case and I don't wish to confuse anyone going forward.

Supporting enumerators is not a trivial matter due to all the options currently supported. Let's take the `:filter` option that searches all the choices for a match. It's not straightforward to make it work with an infinite stream as it needs to search through all the choices at once. In other words, what you're suggesting is vastly incompatible with how the `select` prompt works. The only way I see this being a viable solution is if it was added as an additional prompt type. However, I wonder how common such a need is.
