### ISSUE TITLE
multi_select fails when per_page is specified

### ISSUE THREAD

**Issue by cyclotron3k** [piotrmurach/tty-prompt#51]
`prompt.multi_select('Choose your favourite drink?', {"test": 1, "test2": 2})`
Choose your favourite drink? (Use arrow keys, press Space to select and Enter to finish)
‣ ⬡ test
  ⬡ test2

`prompt.multi_select('Choose your favourite drink?', {"test": 1, "test2": 2}, per_page: 10)`
Choose your favourite drink? (Use arrow keys, press Space to select and Enter to finish)
‣ ⬡ [:test, 1]

**Comment by piotrmurach** [comment]
Hi,
Thanks for using the library and reporting the issue.

Please see the https://github.com/piotrmurach/tty-prompt/issues/46 issue for more details on how to work around it for the time being. This has been fixed in master. I will keep this ticket open in case anybody else finds this issue and close it once I release new version.

**Comment by cyclotron3k** [comment]
I did quickly scan the completed issues but I must have missed that one. Sorry about that.

**Comment by piotrmurach** [comment]
Released `v0.12.0` with the fix. Enjoy!
