### ISSUE TITLE
Keypress with timeout leaves countdown thread running

### ISSUE THREAD

**Issue by kke** [piotrmurach/tty-prompt#56]
..and raises when it reaches zero.

![image](https://cloud.githubusercontent.com/assets/224971/26571536/0c0c4d2a-451f-11e7-90ad-cafa1d72eb13.png)

Reproduce:

```ruby
require 'tty-prompt'

TTY::Prompt.new.keypress("Press any key to continue or ctrl-c to cancel (Automatically continuing in :countdown seconds) ...", timeout: 3)

puts "Continuing"
sleep 5
puts "Will never get here if you pressed a key before reaching zero"
```

**Comment by piotrmurach** [comment]
Hey Kimmo, I've had a break from OSS but I'm back now. Sorry to keep you waiting for this one to be fixed so long. Please could you check out master and let me know if it works for you.

**Comment by kke** [comment]
Seems to work from master

**Comment by piotrmurach** [comment]
Thanks for checking.

On Windows the countdown doesn't actually count and simply waits for input since calling native functions to read keypress from keyboard is blocking and paired with no threading support(at least from Ruby side) makes it really hard to implement this feature. I think it is a reasonable compromise to expect the user to press some key, I will continue investigating if there is a way to have non-blocking input. However, this will work without the countdown as opposed to previous version which didn't work at all on Windows. If you have any ideas on how to have actual countdown, let me know? (I don't want to go down the rabbit hole of actually firing native windows threads :face_with_head_bandage: )

**Comment by kke** [comment]
You can start a thread for the blocking reader and kill it from main once the time has run out or a key has been pressed.

**Comment by piotrmurach** [comment]
Hurray, I've finally fixed the Windows issue with reading single character input thanks to [_kbhit](https://msdn.microsoft.com/en-us/library/58w7c94c.aspx) function. It allowed me to change keypress to be non-blocking which after testing makes Windows work exactly the same as unix-like consoles. The keypress countdown works as expected.
