### ISSUE TITLE
multi select demo does not work on windows when use git-bash

### ISSUE THREAD

**Issue by Sanster** [piotrmurach/tty-prompt#57]
when run [multi select demo](https://github.com/piotrmurach/tty-prompt/blob/master/examples/multi_select.rb) in git-bash on windows, nothing show. 

It works fine when use cmd.exe to run the demo.

I am using `git version 2.12.2.windows.2`

**Comment by piotrmurach** [comment]
Thanks for using the library!

In order for the multi select prompt to work it needs to read input in a raw mode. The problem with `MinTTY`(the bash terminal emulator for cygwin which I assume you are running) is that the check for `$stdout.tty?` is always `false` and hence [this check](https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/reader/mode.rb#L35) fails. Please also refer to [this issue](https://github.com/piotrmurach/tty-prompt/issues/41) where this problem is discussed.

Do you have any suggestions how to work around this problem? I'd be curious to know what the [windows?](https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/reader.rb#L347) check returns under mintty bash emulator? Maybe, we could add some conditions along the lines, use windows console unless it is mintty under cygwin in which case fall back to unix compatible console. However, this still will leaves the question of `$stdout.tty?` check. Any suggestions?

**Comment by Sanster** [comment]
- `windows?` return true.
- A npm library [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) also had this problem years ago, according to the discussion in [issue 272](https://github.com/SBoudrias/Inquirer.js/issues/272) ,it's seems like fixed by nodejs.

**Comment by piotrmurach** [comment]
Hey,

I had a more in depth look at this. It turns out that git-bash on windows emulates bash as `cygwin` compatible emulator. Further, it seem like `$stdout.tty?` always comes back as `true`.  It appears to me that git-bash changes default `isatty` implementation and modifies file descriptor handles for standard streams [see here](https://github.com/git-for-windows/git/blob/master/compat/winansi.c#L472-L605). This should be ok in our case as long as cygwin is detect correctly. I mean I won't be able to make `tty?` check to work as expected as I'm not able to control what emulators tell me, e.i. if they run in interactive mode or not.

Having said all that, running the following in git-bash on windows xp works perfectly fine for me:
```ruby
bundle exec ruby examples/multi_select.rb
```
using `git version 1.7.10.msysgit`

**Comment by Sanster** [comment]
I tested `$stdout.tty?` with `git version 2.12.2.windows.2`, and it always return `false`.

In git-for-windows F&Q, there is a question about pty problem: https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it

**Comment by piotrmurach** [comment]
What shall we do then? Do you know any api call on windows that provides this information accurately? The link you have provided gives solutions which are basically asking you to install external dependency to make the git-bash terminal be more compliant.

**Comment by piotrmurach** [comment]
@Sanster I think we could add a section to readme to explain what can be done to make this work in git bash. Do you have time to write something?

**Comment by piotrmurach** [comment]
As explained in the documentation there are various way to work around the issue.
