### ISSUE TITLE
Answer Collector broken on Windows

### ISSUE THREAD

**Issue by austb** [piotrmurach/tty-prompt#59]
The answer collector is broken on Windows due to the fix for #56. The non-blocking call appears to be causing it to immediately go to the next question in the interview.

![windows_answer_collect](https://user-images.githubusercontent.com/4520807/29330283-9681f78c-81ad-11e7-9340-2fe06cc176a8.gif)

You can see our monkey patch in order to make it work [here](https://github.com/puppetlabs/pdk/commit/4080c9ef973d84c2e85911d411b10b98413b43dc).

**Comment by piotrmurach** [comment]
Thanks, I have realised that I've introduced a breaking change whilst working on the `keypress` timeout feature. Threads and non-blocking IO seem to be much harder than anticipated. Because input is in a infinite loop and when non-blocking IO is used it basically keeps on checking IO for input all the time causing this awful flickerage and breakage. I will revert back to using blocking IO and release a patch which should fix things for you without the need to release new version.

**Comment by austb** [comment]
@piotrmurach just ran the newest master (commit 47599a6) on windows and it looks good. Answer collecting works. All spec tests pass. I'll do some more manual verification after a meeting.

**Comment by piotrmurach** [comment]
I've ensured that all windows examples work fine and especially the [pause example](https://github.com/piotrmurach/tty-prompt/blob/master/examples/pause.rb) plays nicely with windows threads. Extra manual verification will defo help double check if all is fine - thanks.

**Comment by austb** [comment]
I had problems with `keypress.rb` and `pause.rb` that I believe are related to this.

1. `keypress.rb` - terminated immediately with `Answer: nil`
1. `pause.rb` - did not accept `space` or `enter` to continue before timer completed
     - This would allow me to skip the countdown if I pressed `space` or `enter` before the line appeared on screen

**Comment by austb** [comment]
Wait nevermind, scratch that. It works after pulling the most recent change.

**Comment by austb** [comment]
Thanks @piotrmurach ! 👍  It looks good on Windows over here

**Comment by piotrmurach** [comment]
Released `v0.13.1` with the patch. Hopefully a lucky number 😄
