### ISSUE TITLE
Browse "select" list by page?

### ISSUE THREAD

**Issue by orachux** [piotrmurach/tty-prompt#67]
Hello Piotr & community,

I'm using the "select" prompt with a long list (multiple pages) and I'm wondering if it would be somehow possible to page-browse the list similar to the "enum_select" prompt, i.e. pressing page-down key browses to next page of items. 

Motivation: I believe the "select' prompt with it's selected-item marker is more intuitive for users to browse and choose an item, especially with a long list.

In any case, thank you for making and sharing this great piece of work! 

Cheers,

orachux

**Comment by piotrmurach** [comment]
Hello there,

Thank you for using the library! 

I think that adding 'page jumping' to `select` and `multi_select` would be a great addition. There is no reason why they couldn't work the same way as `enum_list` and jump through pages when left/right arrows are pressed, or even pageup/pagedown keys.

Do you have time to work on this and submit PR?

**Comment by orachux** [comment]
I could have a look, but I'm not sure if I'm proficient enough. Wanted to make sure this feature did not exist already. If I understand correctly, it's about implementing a `list_paginator` similar to the `enum_paginator`. Let's see ...

**Comment by piotrmurach** [comment]
It's been a while since I've implemented the `paginator`. I would think that you don't necessarily have to change paginator itself as long as you pass it the next active list element which is at the start of the next page if that makes sense. In other words, I would start from looking into implementing the left & right events so that they figure out the next active element and adjust the slice of choices. It may well require small adjustment to the paginator.

**Comment by piotrmurach** [comment]
@orachux Implemented navigation by page in master branch and will release as part of `v0.19.0` shortly.
